### ISSUE TITLE
Issue in Function

### ISSUE THREAD

**Issue by sjliang20** [HCelion/scrape_write_function#1]
When trying to run this code, I'm getting the following issue:

 Error: Column `rating` must be length 1 or 20, not 0

**Comment by HCelion** [comment]
Thanks, I will have to have a look. My initial guess is that tripadvisor changed their structure and the scraper cannot use it anymore.

**Comment by HCelion** [comment]
Hi, so I took a look and there were two things that caused trouble. 

1. The way the star-ratings are referenced has slightly changed.
2. Reviews can be contested, which means that there are reviewer names with no reviews.

I made changes to the extractor of the star ratings, so it works again.
I also somewhat artificially equalized the lengths of the output of all the extractor functions, such that generating the tibble will not cause an issue. To be fair, this is more hiding the issue than solving it. I am sure there are ways to identify the offending items to be taken out instead.

The code should be working for the time being.
