### ISSUE TITLE
scrape_write_table error

### ISSUE THREAD

**Issue by CMilligan95** [HCelion/scrape_write_function#3]
Hello,

I get the following error when running line 146:

 Error in write_delim(x, path, delim = "\t", na = na, append = append,  : 
  is.data.frame(x) is not TRUE

Is there any way that you might be able to help me with this?

**Comment by HCelion** [comment]
Yeah, the scraper is currently out of date. I guess one of these evenings/weekends I will have to update it to work again.

**Comment by CMilligan95** [comment]
Ah okay, I was worried that I was missing something! Thank you for this tutorial- I use Trust Pilot for work so the option to pull data from the site is amazing :)

**Comment by HCelion** [comment]
Hi,
The website really changed its format significantly. The data comes now in a JSON like format and R was a bit too clumsy to use. I rewrote the scraper in Python. The code is easier to understand and more maintainable that way as well. Hope it is still useful.
